apiVersion: apps/v1
kind: Deployment
metadata:
  name: week2-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: week2-app
  template:
    metadata:
      labels:
        app: week2-app
    spec:
      imagePullSecrets:
        - name: nexus-registry-secret
      containers:
        - name: week2-app
          image: nexus.example.com:8082/devops/week2-app:latest
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
