stages:
  - build
  - deploy

variables:
  IMAGE_NAME: $IMAGE_NAME

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - echo $NEXUS_PASSWORD | docker login -u $NEXUS_USER --password-stdin $REGISTRY_URL
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - main

deploy:
  stage: deploy
  script:
    - kubectl apply -f k8s/
  only:
    - main
