stages:
  - test
  - build
  - deploy

variables:
  IMAGE_TAG: $NEXUS_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  script:
    - docker login -u "$NEXUS_USER" -p "$NEXUS_PASSWORD" $NEXUS_REGISTRY
    - docker build -t $NEXUS_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA -f app/Dockerfile .
    - docker push $NEXUS_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA
  only:
    - main
  tags:
    - docker

deploy:
  stage: deploy
  image: docker.arvancloud.ir/dtzar/helm-kubectl:latest
  before_script:
    - echo "$KUBE_CONFIG" > kubeconfig.yaml
    - export KUBECONFIG=$PWD/kubeconfig.yaml
  script:
    - sed "s|IMAGE_PLACEHOLDER|$IMAGE_TAG|g" k8s/deployment.yaml | kubectl apply -f - 
    - kubectl apply -f k8s/service.yaml && kubectl apply -f k8s/ingress.yaml
  only:
    - main
  tags:
    - docker
