stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  script:
    - docker build -t registry.yourdomain.com/your-repo/image:latest .
    - docker push registry.yourdomain.com/your-repo/image:latest

deploy:
  stage: deploy
  image: alpine/helm:3.12.0
  script:
    - helm upgrade --install myapp ./helm/myapp --namespace mynamespace --create-namespace
  only:
    - main
